### ISSUE TITLE
reading first line 

### ISSUE THREAD

**Issue by Zodthe** [rgx91/BWTool#1]
great work but there is an issue when running it can only  read the first bitcoin address , ignoring the wrest

**Comment by rgx91** [comment]
Thank you so much, I fixed this and other bugs as well!
I cant belive i made this mistake duh :=(

**Comment by Zodthe** [comment]
great job , any plans on making a gpu version ??

**Comment by rgx91** [comment]
> great job , any plans on making a gpu version ??

Well it is possible a feature release has this feature, but I should implement other tools before.
