### ISSUE TITLE
Using multiple processor cores.

### ISSUE THREAD

**Issue by Dimitrius1** [rgx91/BWTool#4]
Hi, I think it would be nice if you added the ability to use multiple processor cores (with the ability to manually specify how many cores should be used). Now, as I understand it, only 1 core is used.
It's also a good idea to add GPU computation support. But I think it will take longer.

**Comment by rgx91** [comment]
There are tools out there which are far, far, multiple times faster than this approach.
There will be no significant performance gain if we run this on multiple core.
Keep in mind, I was just curious it is possible run this kind of things in C#, its not better than a tech demo.
However a GPU support could be interesting, but I dont have the experience in it.
