### ISSUE TITLE
What does Count of sha256 operation on string means?

### ISSUE THREAD

**Issue by jeong760** [rgx91/BWTool#5]
Dears,

May you give me an answer about what does Count of sha256 operation on string means?
Is it for how many dictionary digits I use for brain wallet cracking?

Just wonder if how I use this option

Best Regards,
John Ahn

**Comment by rgx91** [comment]
Hello jeong760,
it means the repeated depth of sha256 operation on a string.
For example if you choose 2 operation, it will converting the string to hash and repeats the sha256 op on the hash.
It is good if you target brainwallet addresses generated from a hash, generated from a string.

**Comment by jeong760** [comment]
Thanks for the kind explanation.
